<?php
if (!defined('ABSPATH')) exit;
class XP_TI_REST {
    public static function init(){ add_action('rest_api_init',[__CLASS__,'routes']); }
    public static function routes(){ register_rest_route('xplore/v1','/travel-itineraries',['methods'=>'GET','callback'=>[__CLASS__,'list'],'permission_callback'=>'__return_true']); register_rest_route('xplore/v1','/travel-itineraries/(?P<id>\d+)',['methods'=>'GET','callback'=>[__CLASS__,'get'],'permission_callback'=>'__return_true']); register_rest_route('xplore/v1','/travel-itineraries/slug/(?P<slug>[a-zA-Z0-9-]+)',['methods'=>'GET','callback'=>[__CLASS__,'slug'],'permission_callback'=>'__return_true']); }
    private static function base($p){return ['id'=>$p->ID,'title'=>$p->post_title,'slug'=>$p->post_name,'description'=>wp_strip_all_tags($p->post_content),'excerpt'=>get_the_excerpt($p),'featured_image'=>get_the_post_thumbnail_url($p->ID,'large')?:'','destination'=>get_post_meta($p->ID,'_xp_ti_destination',true),'duration_days'=>(int)get_post_meta($p->ID,'_xp_ti_days',true),'style'=>get_post_meta($p->ID,'_xp_ti_style',true),'budget'=>get_post_meta($p->ID,'_xp_ti_budget',true),'best_time'=>get_post_meta($p->ID,'_xp_ti_best_time',true),'booking_enabled'=>get_post_meta($p->ID,'_xp_ti_booking_enabled',true)==='1','updated_at'=>get_post_modified_time('c',true,$p->ID)];}
    private static function listing($id){$p=get_post($id); if(!$p||$p->post_type!=='listing'||$p->post_status!=='publish') return null; $img=get_the_post_thumbnail_url($id,'large')?:''; return ['id'=>$id,'title'=>$p->post_title,'slug'=>$p->post_name,'url'=>get_permalink($id),'image'=>$img,'excerpt'=>wp_strip_all_tags(get_the_excerpt($id))];}
    private static function hydrate($p){$r=self::base($p);$r['days']=[];$data=get_post_meta($p->ID,'_xp_ti_days_data',true); foreach((array)$data as $day_no=>$day){$items=[];foreach((array)($day['items']??[]) as $item){$items[]=['time'=>$item['time']??'','activity'=>$item['activity']??'','duration'=>(int)($item['duration']??0),'notes'=>$item['notes']??'','listing_id'=>(int)($item['listing_id']??0),'listing'=>self::listing((int)($item['listing_id']??0))];}$r['days'][]=['day'=>(int)$day_no,'title'=>$day['title']??('Day '.$day_no),'description'=>$day['description']??'','items'=>$items];}return $r;}
    public static function list(){ $q=new WP_Query(['post_type'=>'xp_itinerary','post_status'=>'publish','posts_per_page'=>50,'orderby'=>'date','order'=>'DESC']);$out=[];foreach($q->posts as $p)$out[]=self::base($p);return rest_ensure_response($out); }
    public static function get($request){$p=get_post((int)$request['id']);if(!$p||$p->post_type!=='xp_itinerary'||$p->post_status!=='publish')return new WP_Error('not_found','Itinerary not found',['status'=>404]);return rest_ensure_response(self::hydrate($p));}
    public static function slug($request){$p=get_page_by_path(sanitize_title($request['slug']),OBJECT,'xp_itinerary');if(!$p||$p->post_status!=='publish')return new WP_Error('not_found','Itinerary not found',['status'=>404]);return rest_ensure_response(self::hydrate($p));}
}
