<?php
if (!defined('ABSPATH')) exit;
class XP_TI_WooCommerce {
    public static function init(){ add_action('save_post_xp_itinerary',[__CLASS__,'sync_product'],20,2); add_filter('woocommerce_add_cart_item_data',[__CLASS__,'cart_data'],10,3); add_filter('woocommerce_get_item_data',[__CLASS__,'display_cart_data'],10,2); add_action('woocommerce_checkout_create_order_line_item',[__CLASS__,'order_item'],10,4); }
    public static function sync_product($post_id,$post){ if(wp_is_post_revision($post_id)||!class_exists('WooCommerce')) return; $enabled=get_post_meta($post_id,'_xp_ti_booking_enabled',true); if($enabled!=='1') return; $product_id=absint(get_post_meta($post_id,'_xp_ti_wc_product_id',true)); $product=$product_id?wc_get_product($product_id):false; if(!$product){$product=new WC_Product_Simple();} $product->set_name($post->post_title); $product->set_status('publish'); $product->set_catalog_visibility('hidden'); $product->set_virtual(true); $product->set_sold_individually(false); $product->set_price((float)get_post_meta($post_id,'_xp_ti_adult_price',true)); $product->set_regular_price((float)get_post_meta($post_id,'_xp_ti_adult_price',true)); $product->update_meta_data('_xp_ti_itinerary_id',$post_id); $product->save(); update_post_meta($post_id,'_xp_ti_wc_product_id',$product->get_id()); }
    public static function cart_data($data,$product_id,$variation_id){$it=absint(get_post_meta($product_id,'_xp_ti_itinerary_id',true)); if($it){$data['xp_ti_itinerary_id']=$it;$data['xp_ti_booking_token']=wp_generate_uuid4();} return $data;}
    public static function display_cart_data($item_data,$cart_item){ if(!empty($cart_item['xp_ti_itinerary_id'])) $item_data[]=['key'=>'Itinerary','value'=>get_the_title($cart_item['xp_ti_itinerary_id'])]; return $item_data; }
    public static function order_item($item,$cart_item_key,$values,$order){ if(!empty($values['xp_ti_itinerary_id'])){$item->add_meta_data('_xp_ti_itinerary_id',absint($values['xp_ti_itinerary_id']),true);$item->add_meta_data('_xp_ti_booking_token',sanitize_text_field($values['xp_ti_booking_token']??''),true);} }
}
